In [2]:
import sys
import os

# Add the parent directory of the current notebook to sys.path
sys.path.append(os.path.abspath(os.path.join('..', 'Foundational Models')))

# Now you can import your module
import mlp
import numpy as np


In [11]:
softmax = mlp.Softmax

data = np.array([0.2, 1.5, 2.2, -0.1, 0.8]).reshape(-1,1)

data
#s = softmax.forward(softmax, data)

#s

array([[ 0.2],
       [ 1.5],
       [ 2.2],
       [-0.1],
       [ 0.8]])

In [28]:
s.shape

# This (or something approximating it) is good for one sample.
np.einsum("ij, jk -> ik", s, -s.T)

array([[-0.00467766, -0.01716372, -0.03456349, -0.0034653 , -0.00852325],
       [-0.01716372, -0.06297879, -0.1268237 , -0.0127152 , -0.03127434],
       [-0.03456349, -0.1268237 , -0.25539157, -0.02560526, -0.06297879],
       [-0.0034653 , -0.0127152 , -0.02560526, -0.00256715, -0.00631418],
       [-0.00852325, -0.03127434, -0.06297879, -0.00631418, -0.01553038]])

In [3]:
data = np.array([[-0.2, 1.5, -0.1, 2.2, 0.8],[0.1,-0.9,2.1,-0.3,-0.9]]).transpose()

print(data)

exps = np.exp(data)
summed_exps = np.einsum("ij -> j", exps)

print(summed_exps)

print("Division : \n",exps / summed_exps)

print("Vectorwise vivision : \n",exps/summed_exps[:])

softmax = mlp.Softmax

softmax.forward(softmax, data)

[[-0.2  0.1]
 [ 1.5 -0.9]
 [-0.1  2.1]
 [ 2.2 -0.3]
 [ 0.8 -0.9]]
[17.45581167 10.82529837]
Division : 
 [[0.04690305 0.1020915 ]
 [0.25674481 0.03755736]
 [0.05183588 0.7543598 ]
 [0.51702056 0.06843398]
 [0.1274957  0.03755736]]
Vectorwise vivision : 
 [[0.04690305 0.1020915 ]
 [0.25674481 0.03755736]
 [0.05183588 0.7543598 ]
 [0.51702056 0.06843398]
 [0.1274957  0.03755736]]


array([[0.04690305, 0.1020915 ],
       [0.25674481, 0.03755736],
       [0.05183588, 0.7543598 ],
       [0.51702056, 0.06843398],
       [0.1274957 , 0.03755736]])

In [10]:
np.einsum("bij, bj -> bi", s, -s.T)

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

In [9]:
data

# data = np.array([[-0.2, 1.5, -0.1, 2.2, 0.8],[0.1,-0.9,2.1,-0.3,-0.9]]).transpose()

a = mlp.Softmax

print(data)
print(a.forward(a,data))

s = a.forward(a,data)

# rows and columns x columns and rows
#
# m x 1 x n  .  1 x m x n
#
#
s_3D = s[:,:,np.newaxis].transpose(0,2,1)
s_3D_T = s_3D.transpose(1,0,2)


print("")
print(s_3D.shape)
print(s_3D_T.shape)

jacobian_stack = np.einsum("bij,bj->bi", s_3D, s_3D_T)

jacobian_stack.shape

[[-0.2  0.1]
 [ 1.5 -0.9]
 [-0.1  2.1]
 [ 2.2 -0.3]
 [ 0.8 -0.9]]
[[0.04690305 0.1020915 ]
 [0.25674481 0.03755736]
 [0.05183588 0.7543598 ]
 [0.51702056 0.06843398]
 [0.1274957  0.03755736]]

(5, 1, 2)
(1, 5, 2)


ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.